### ISSUE TITLE
May I ask which parameters can be adjusted to make it run on se2020 of iOS14.6.

### ISSUE THREAD

**Issue by xhaaa** [LNSSPsd/PodsGrant#1]
May I ask which parameters can be adjusted to make it run on se2020 of iOS14.6.

**Comment by LNSSPsd** [comment]
You can analyze `bluetoothd` of your version of iOS and try to get it worked. Searching "AirPods" inside that binary could help.

**Comment by dqdd123** [comment]
I've got the bluetoothd file located under /usr/sbin, may I ask how to analyze it, I really want to use AirPods pro2 with my iphone12 of  ios14.4, thanks a lot!

[bluetoothd.zip](https://github.com/LNSSPsd/PodsGrant/files/11085781/bluetoothd.zip)

**Comment by dqdd123** [comment]
Really appreciate that！！
