### ISSUE TITLE
bluetoothd 14.x.x arm64e

### ISSUE THREAD

**Issue by Symplicityy** [LNSSPsd/PodsGrant#16]
This should be the every missing version of iOS 14 for arm64e devices. I will try to do arm64 next if I have time. 
[bluetoothd14.x.x.zip](https://github.com/LNSSPsd/PodsGrant/files/11186224/bluetoothd14.x.x.zip)

**Comment by rastafaa** [comment]
That’s awesome but can arm64e devices even jailbreak on all those 14 versions?

**Comment by Symplicityy** [comment]
> That’s awesome but can arm64e devices even jailbreak on all those 14 versions?

According to https://unc0ver.dev yes. It supports 11.0-14.8

**Comment by LNSSPsd** [comment]
Thanks. Closed as completed.
