### ISSUE TITLE
Could this be done for AirPods 3?

### ISSUE THREAD

**Issue by combustor** [LNSSPsd/PodsGrant#19]
Hi, this tweak seems amazing

I just have a question, could this be done to the AirPods 3? Would it be as easy as adding a couple of lines? 

Thank you for your work

**Comment by LNSSPsd** [comment]
Could be possible. Would give a try later but I can't test with it, would you be able to build from the source code by yourself?

**Comment by combustor** [comment]
> Could be possible. Would give a try later but I can't test with it, would you be able to build from the source code by yourself?

I unfortunately only have a windows machine 

But if you want me to test something I would be happy to do it

**Comment by rastafaa** [comment]
> I unfortunately only have a windows machine

You can compile in Windows.. I've been doing it using theos, just need to install linux subsystem in windows (thru powershell and cpu virtualization)

**Comment by combustor** [comment]
> > I unfortunately only have a windows machine
> 
> 
> 
> You can compile in Windows.. I've been doing it using theos, just need to install linux subsystem in windows (thru powershell and cpu virtualization)

Ah if that's the case then yes I would be able to build it

**Comment by LNSSPsd** [comment]
Have a try on the latest commit.

**Comment by combustor** [comment]
> Have a try on the latest commit.

I have installed it and it works, the AirPods are actually detected as AirPods instead of unknown device

I can now see the AirPods battery

All features that required AirPods (like LiveListen) now work

There's still no case pop up but that's okay

Also I have a question, wouldn't it be better to treat them as AirPods Pro rather than AirPods 2? 

The AirPods 3 and Pro practically look the same and they share most features 

Thank you for your work

**Comment by LNSSPsd** [comment]
> There's still no case pop up but that's okay

I'm not sure but maybe try killing `SharingViewService`?

> Also I have a question, wouldn't it be better to treat them as AirPods Pro rather than AirPods 2?

Idk how it would act being treated as AirPods Pro, just try replacing `8207` to `0x200E` on both of the `.x` files and see if it's better.

**Comment by combustor** [comment]
> I'm not sure but maybe try killing `SharingViewService`?

I did ldrestart and it now works

> Idk how it would act being treated as AirPods Pro, just try replacing `8207` to `0x200E` on both of the `.x` files and see if it's better.

Alright I did that and see no real difference

But the pop up now shows the AirPods Pro yet the icons are still AirPods 2
