### ISSUE TITLE
Heres Bluetoothd for 14.3 arm64 (iPhone 7)

### ISSUE THREAD

**Issue by NotAnEvilScientist** [LNSSPsd/PodsGrant#20]
[bluetoothd.zip] (https://github.com/LNSSPsd/PodsGrant/files/11190452/bluetoothd.zip)

**Comment by NotAnEvilScientist** [comment]
hmm, that’s weird, I pulled it strait from the folder it was in. It’s probably my computer doing something to it or that I attached the file via a link. It wouldn’t let me attach it without using a link

**Comment by LNSSPsd** [comment]
> here’s mine, iPhone 8 14.3
> 
> [bluetoothd.zip](https://github.com/LNSSPsd/PodsGrant/files/11192461/bluetoothd.zip)

Thanks.
