### ISSUE TITLE
Does it work on xina？

### ISSUE THREAD

**Issue by xkcxkc** [LNSSPsd/PodsGrant#21]

**Comment by LNSSPsd** [comment]
Technically it does.

**Comment by xkcxkc** [comment]
Then how do I use it on xina，which version should I use？I ever tried to install both of version respectively but it still not work。my facility is iphone11 ios15.1 xina 1.7.2

**Comment by xkcxkc** [comment]
> Technically it does.

Then how do I use it on xina，which version should I use？I ever tried to install both of version respectively but it still not work。my facility is iphone11 ios15.1 xina 1.7.2

**Comment by xkcxkc** [comment]
> Technically it does.

Then how do I use it on xina，which version should I use？I ever tried to install both of version respectively by filza but it still not work。my facility is iphone11 ios15.1 xina 1.7.2

**Comment by LNSSPsd** [comment]
Is Filza working on deb installation? For me Filza's dpkg installation does nothing than showing an empty dialog.

**Comment by xkcxkc** [comment]
> Is Filza working on deb installation? For me Filza's dpkg installation does nothing than showing an empty dialog on iOS 15.3.

Thank you for your reply. Actually, I am a layman. May I ask you to make a version that fits in XinaA15? Sorry for disturbing you if you are really busy or you don’t have XinaA15 facilities. It’s really important for me🙃. I have been waiting for this tweak every day since I bought AirPods Pro2.

**Comment by Kimo1126** [comment]
Just install it via saily, and then with filza go to dpkg folder and edit the statut file, search for podsgrant and Change ''Architecture: iphoneos-arm64'' to ''Architecture: iphoneos-arm''
And save it .

**Comment by xkcxkc** [comment]
> Just install it via saily, and then with filza go to dpkg folder and edit the statut file, search for podsgrant and Change ''Architecture: iphoneos-arm64'' to ''Architecture: iphoneos-arm''
> And save it .

Even though you have explained it very detailedly, I still failed. Can you tell me what I should do next? I tried to download the ios14 version from github and install it with filza, but I couldn’t find podsgrant in the dpkg/status.🥺Please forgive my stupidity.
![image](https://user-images.githubusercontent.com/79241548/231330532-1b3b2ad0-d0dc-44e3-82ca-eb0f4e907c3a.png)

**Comment by xkcxkc** [comment]
> Is Filza working on deb installation? For me Filza's dpkg installation does nothing than showing an empty dialog on iOS 15.3.

I followed what another friend said and used filza to unzip rootless.deb and changed architecture: iphoneos-arm64 in DEBIAN/control to iphoneos-arm, then repackaged it into deb and installed it. The icon is displayed correctly, but the pop-up window has not appeared yet. What should I do next? Thank you for your review first.
