### ISSUE TITLE
iOS 15.4.1 (actually) bluetoothd 

### ISSUE THREAD

**Issue by Mattjab11** [LNSSPsd/PodsGrant#23]
Here is the [bluetoothd.zip](https://github.com/LNSSPsd/PodsGrant/files/11194470/bluetoothd.zip) for 15.4.1, not 15.4.
I installed the rootless tweak and my volume slider shows the AirPods icon but I still don’t have the pop-up. (iPhone 12 iOS 15.4.1 —A2698)

**Comment by babyf2sh** [comment]
15.4和15.41蓝牙文件是一样的，你没效果估计是因为xina。

**Comment by LNSSPsd** [comment]
The pop-up is not such address-based and I guess this issue is hooking related.

**Comment by rastafaa** [comment]
Check to see if you have the tweak injected into sharingd

**Comment by LNSSPsd** [comment]
> Check to see if you have the tweak injected into sharingd

Actually I've already put a `postinst` script to kill `sharingd` right after installation, so I'm not really sure what went wrong.

**Comment by stylesbeyond** [comment]
> Here is the [bluetoothd.zip](https://github.com/LNSSPsd/PodsGrant/files/11194470/bluetoothd.zip) for 15.4.1, not 15.4.
> I installed the rootless tweak and my volume slider shows the AirPods icon but I still don’t have the pop-up. (iPhone 12 iOS 15.4.1 —A2698)

where does this file go? thanks

**Comment by LNSSPsd** [comment]
It's the problem with failing to hook, trying to kill `sharingd` and `SharingViewService` may help.
The pop-up has no relationship with addresses, it is based on an objective-c hook.

**Comment by stylesbeyond** [comment]
> 

How does one kill those services.

**Comment by LNSSPsd** [comment]
```
killall -TERM sharingd
killall -TERM SharingViewService
```
