### ISSUE TITLE
add ios 15.2.1

### ISSUE THREAD

**Issue by sileovn** [LNSSPsd/PodsGrant#25]
hi bro, you are add ios 15.2.1 thanks much

**Comment by LNSSPsd** [comment]
I need the `bluetoothd` binary.

**Comment by hoanmaster321** [comment]
please show me how to get it. I'll help you

**Comment by hoanmaster321** [comment]
[bluetoothd.zip](https://github.com/LNSSPsd/PodsGrant/files/11298934/bluetoothd.zip)
 ios 15.2.1 . bluetoothd

**Comment by LNSSPsd** [comment]
> [bluetoothd.zip](https://github.com/LNSSPsd/PodsGrant/files/11298934/bluetoothd.zip) ios 15.2.1 . bluetoothd

Thank you.
