### ISSUE TITLE
Keyboard breaks after installing

### ISSUE THREAD

**Issue by mkwiimaster7** [LNSSPsd/PodsGrant#28]
When i install the tweak, the keyboard breaks in all my apps and causes them to not register my taps

Edit: forgot to mention im on Fugu15 Max, iPhone 12, iOS 15.1.1

**Comment by LNSSPsd** [comment]
Is it caused by this tweak? This tweak has nothing to do with keyboard.
Just reboot, re-jailbreak and kill those daemons again and see.

**Comment by mkwiimaster7** [comment]
> Is it caused by this tweak? This tweak has nothing to do with keyboard.
> 
> Just reboot, re-jailbreak and kill those daemons again and see.

yes i did that, it doesnt happen on initial install, only after you reboot and rejb or userspace reboot. and yes i have confirmed this tweak causes the issue
