### ISSUE TITLE
13 Pro Max / iOS 15.4.1 No AirPods Pop-up

### ISSUE THREAD

**Issue by TheRealClarity** [LNSSPsd/PodsGrant#29]
I have the AirPods Pro 2.
I've installed the latest version and userspace rebooted, manually killed sharingd, bluetoothd and whatnot, and the popup still doesn't show. On the battery widget, the case shows up as a regular device, instead of the airpods case, so I think it might not be getting spoofed properly. The AirPods seem ok, they even show up at the control center, and their functionality looks fine.
How can I (help) debug this further?

**Comment by LNSSPsd** [comment]
Oh, I see, the interface seems to be different on higher versions.

**Comment by LNSSPsd** [comment]
This should be solved at 7c66ab3.
Closed as completed

**Comment by TheRealClarity** [comment]
Thank you!

**Comment by rob311fan** [comment]
dude, you fixed it. popup and battery both show correctly now. tested on ipad 1.5.4 and iphone 12 15.4.1

thank you for your hard work

**Comment by stylesbeyond** [comment]
> This should be solved at [7c66ab3](https://github.com/LNSSPsd/PodsGrant/commit/7c66ab359225167b506e41d1ff593e8042757b2a).
> Closed as completed

I don't see the update?

**Comment by stylesbeyond** [comment]
> dude, you fixed it. popup and battery both show correctly now. tested on ipad 1.5.4 and iphone 12 15.4.1
> 
> thank you for your hard work

hi, where can I find the deb I don't see it on releases
