### ISSUE TITLE
iPhone 13 Pro Max 15.1 the pop up gets stuck at holding the button on the AirPods

### ISSUE THREAD

**Issue by NJ174** [LNSSPsd/PodsGrant#31]
Besides that everything else seems to be ok except FindMy. 

Here is the link to my bluetoothd 15.1 (A2484) https://mega.nz/file/U1tGzQgR#5anlEtA7JQnIVq_yf8l7Xe8k2TPkORVXZrDNHl_LtMM

Just wanted to say great work!!! It saved me from returning my new AirPods.

**Comment by LNSSPsd** [comment]
FindMy and the popup based cloud pairing are not intended to be working (as I haven't found a way to make them work) currently.
You would have to pair through the bluetooth settings UI.

**Comment by NJ174** [comment]
Ok, so I do have another iPhone X on 16.4.1 and after pairing under the same Apple ID it shows in FindMy on 15.1. Ping doesn't work for the case but it works for the pods both L and R ping. 

The only other thing is they haven't updated yet still on 5B58.
