### ISSUE TITLE
Heres bluetoothd for 15.6.1, arm64 (iPhone 8)

### ISSUE THREAD

**Issue by NotAnEvilScientist** [LNSSPsd/PodsGrant#43]
[bluetoothd 2.zip](https://github.com/LNSSPsd/PodsGrant/files/11523291/bluetoothd.2.zip)

**Comment by NotAnEvilScientist** [comment]
Bluetooth file for iPhone 8

**Comment by LNSSPsd** [comment]
Thank you.
Closed as completed.
