### ISSUE TITLE
[Request] Support for Beats Studio Buds +

### ISSUE THREAD

**Issue by Dr-Sauce** [LNSSPsd/PodsGrant#45]
.

**Comment by LNSSPsd** [comment]
I would like to know the target prior version it's going to be.
For example: AirPods Pro 2nd Gen. goes 1st Generation
Thanks.

**Comment by Dr-Sauce** [comment]
Spoof Beats Studio Buds Plus as AirPods Pro 1st generation.

**Comment by LNSSPsd** [comment]
Wow it's courageous to try inter-brand fooling!
I'm not sure that it would ever work but will give it a try, as an option or something like that later.

**Comment by Dr-Sauce** [comment]
I actually think you can try spoofing Beats Studio Buds as Beats Studio Buds Plus.

Just checked the release days and iOS 15 has Beats Studio Buds.

![2AA91C12-83CB-4492-ACE4-43471C82B749](https://github.com/LNSSPsd/PodsGrant/assets/82555878/70fed392-cf0c-4fb9-b3a4-7a6242b70740)

**Comment by Dr-Sauce** [comment]
(Edited some typos)

**Comment by LNSSPsd** [comment]
> Nevermind. Actually I think you can try spoofing Beats Studio Buds Plus as Beats Studio Buds.
> 
> Just checked the release days and iOS 15 has Beats Studio Buds.
> 
> ![2AA91C12-83CB-4492-ACE4-43471C82B749](https://user-images.githubusercontent.com/82555878/243156917-70fed392-cf0c-4fb9-b3a4-7a6242b70740.jpeg)

Oh that would be definitely better, thanks for information!

**Comment by Dr-Sauce** [comment]
Thanks.! Can you upload the updated version to releases?

**Comment by LNSSPsd** [comment]
> Thanks.! Can you upload the updated version to releases?

Of course.
[Here you go](https://github.com/LNSSPsd/PodsGrant/releases/tag/0.2.4).

**Comment by Dr-Sauce** [comment]
I think there’s something wrong with the code. It doesn’t recognise Beats Studio Buds + as Beats Studio Buds. It recognises it as a unknown device. (I’m on iOS 15.2, Dopamine rootless)

Adaptive transparency mode appears in settings though. (But this option also appeared on PodsGrant 0.2.3 which doesn’t have the new code)

![AF09F31C-3E1F-4526-970B-B496391ECED2](https://github.com/LNSSPsd/PodsGrant/assets/82555878/96c53c70-29c4-4458-8fea-7e107f3b6e6a)

![8B0F48B8-5CD4-4F8C-A7A0-1D0EF0313CF3](https://github.com/LNSSPsd/PodsGrant/assets/82555878/9e49f022-0be9-420e-a56e-c5f6dc671469)

**Comment by LNSSPsd** [comment]
I am sorry to hear that, and there could be something wrong identifying the device. I will check it later and thank you for the information.

**Comment by LNSSPsd** [comment]
Oh, I see, it's something wrong on my side. The non-rootless binary is packed in rootless package.
Try the new package in [Releases](../releases) out.

**Comment by Dr-Sauce** [comment]
Hmm.. It still appears like this. Maybe there’s a different problem.

![BA2E1EAF-23B3-4DA9-AF68-8B6B5864649C](https://github.com/LNSSPsd/PodsGrant/assets/82555878/445f94f2-9fa7-4f77-a65e-dadb02fbbe3b)

**Comment by LNSSPsd** [comment]
Could you try _this_ out, whose logging is enabled? Usage: Install, pair, and then check for `/tmp/bluetoothd.log` to see the product ID. 
[com.lns.pogr_0.2.4-1+debug_iphoneos-arm64.deb.zip](https://github.com/LNSSPsd/PodsGrant/files/11765586/com.lns.pogr_0.2.4-1%2Bdebug_iphoneos-arm64.deb.zip)

**Comment by Dr-Sauce** [comment]
[bluetoothd.txt](https://github.com/LNSSPsd/PodsGrant/files/11765666/bluetoothd.txt)

**Comment by LNSSPsd** [comment]
Thanks a lot, and try the [new package](https://github.com/LNSSPsd/PodsGrant/releases/tag/0.2.4) out!

**Comment by Dr-Sauce** [comment]
![7B1A2DC5-32CF-493B-BE3C-FE1DF67E221C](https://github.com/LNSSPsd/PodsGrant/assets/82555878/f836c010-5ac5-43a2-b8f9-3850300565fb)

**Comment by LNSSPsd** [comment]
> ![7B1A2DC5-32CF-493B-BE3C-FE1DF67E221C](https://user-images.githubusercontent.com/82555878/246306111-f836c010-5ac5-43a2-b8f9-3850300565fb.png)

Wow, didn't know the product for which I set the ID as is such a huge headset! Sorry for getting the product ID wrong!
Try `ROOTLESS_3_com.lns.pogr_0.2.5_iphoneos-arm64.deb` out.

**Comment by Dr-Sauce** [comment]
Wow, big thanks! It’s working now! Now I can check the battery when I open the case.

![D3B2F1D4-1B68-49E8-9464-90B89E279EFF](https://github.com/LNSSPsd/PodsGrant/assets/82555878/a2a8f538-6b5a-485e-a078-3c26785d0d2a)

![5349EF86-FFA2-4C8F-9EF7-BF45E7DC2BE5](https://github.com/LNSSPsd/PodsGrant/assets/82555878/8772e9ac-f9c9-4ac3-9d26-c3d0f7b5587c)

**Comment by LNSSPsd** [comment]
Good for you!
