### ISSUE TITLE
14.8 support? 🙏 (bluetoothd attached)

### ISSUE THREAD

**Issue by rastafaa** [LNSSPsd/PodsGrant#5]
This tweak is exactly what I was looking for but I see 14.8 isn’t currently supported :(

I'm attaching my bluetoothd.. I had to add file extension to get it to upload but just remove it

[bluetoothd.md](https://github.com/LNSSPsd/PodsGrant/files/11133927/bluetoothd.md)

Thank you!!!

**Comment by rastafaa** [comment]
[bluetoothd.zip](https://github.com/LNSSPsd/PodsGrant/files/11133933/bluetoothd.zip)

Here’s the zip if you prefer

**Comment by LNSSPsd** [comment]
Done, and thanks for binary.

**Comment by rastafaa** [comment]
Any idea when this will get released to or by bigboss? Or should I try compiling it myself again.. I wasn’t able to compile without errors on my previous attempts

**Comment by LNSSPsd** [comment]
Could be in a week.

**Comment by rastafaa** [comment]
I was able to compile the tweak now and install it, my airpods are showing now as connected (and appears in accessibility) but the popup and volume control aren't working. I think the code is treating my device like it's rootless but it's actually rootful? When I compiled it gave some error about not finding rootful directory so not sure what that means.

**Comment by LNSSPsd** [comment]
> I was able to compile the tweak now and install it, my airpods are showing up (and appears in accessibility) but the popup and volume control aren't working.
> 
> Also when I close the case the battery widget switches to showing generic headphones.

For volume control you would have to install rocketbootstrap and respring, not really sure why it wasn't working as it works in my device. But it's going to be reimplemented, either in the correct way (may require extra binaries so it's kind of hard) or just by a socket, as IPC doesn't work for iOS 15.

The popup was implemented in a buggy way as well, hopefully it would be reimplemented soon, if possible.

**Comment by rastafaa** [comment]
Thanks I'll check it out soon! Fyi, I noticed that tweak isn't getting injected into sharingd for some reason so maybe had something to do with volume issue? I killed the daemon but it restarts without the module loaded in

**Comment by rastafaa** [comment]
After installing new tweak and restarting phone the popup works perfectly! Except volume control still doesn't and then after re-pairing the airpods it no longer shows up as airpods icons and doesn't appear in accessibility menu haha.. seems popup was fixed but everything else stopped working. I'll try messing with it some more.

**Comment by LNSSPsd** [comment]
What's your iOS version, is it exactly iOS 14.8?
I think it could be caused by the strict version check in my code.

**Comment by rastafaa** [comment]
After going back to old version forgetting, changing name of airpods re-pairing etc., and re-installing newest version of tweak all the old stuff works again, plus the pop-up, but still no volume changing. I think the issue above was caused by accessory model somehow getting changed to "accessory_something" instead of "airpod Pros".. but now it's back to normal.

My version just says 14.8 (18H17)

**Comment by rastafaa** [comment]
![image](https://user-images.githubusercontent.com/37600342/230682804-211cbef6-a696-43e7-96d5-d50e1981b2c0.png)

I do get this error several times when I compile is this any problem?

**Comment by LNSSPsd** [comment]
That's fine, ignore it.

**Comment by LNSSPsd** [comment]
> After going back to old version forgetting, changing name of airpods re-pairing etc., and re-installing newest version of tweak all the old stuff works again, plus the pop-up, but still no volume changing. I think the issue above was caused by accessory model somehow getting changed to "accessory_something" instead of "airpod Pros" when I paired on the new version, but now it's back to normal. However it might only be fixed because I paired it while on older version.
> 
> My version just says 14.8 (18H17)
> 
> fyi spatial tracking also doesn't seem to track anywhere just stays virtually in one spot

Have you tried that one in the Releases?

**Comment by rastafaa** [comment]
> Have you tried that one in the Releases?
No I didn't see that I'll try it now

**Comment by rastafaa** [comment]
Unfortunately no difference

Here’s log of me swiping airpod volume gesture one time (down)
![3C78D120-E817-46EF-9790-6534446E6153](https://user-images.githubusercontent.com/37600342/230685226-ae025415-7ce2-4878-bbc4-716943eda8c1.jpeg)

**Comment by rastafaa** [comment]
Also seeing it from mediaserver 

![63EFE4A9-7026-47EF-93EC-A13F39D85F0A](https://user-images.githubusercontent.com/37600342/230685720-ef26a3cd-86c0-4e46-ab73-e14c9720675b.jpeg)

**Comment by rastafaa** [comment]
![D277A799-68A4-4559-B64A-7C28BE63AEF2](https://user-images.githubusercontent.com/37600342/230685889-895fd2df-2ba2-4e42-b03e-3a43d3b16f36.jpeg)

**Comment by rastafaa** [comment]
I'm not an expert but as far as I can tell, bluetoothd instructs mediaserverd to change volume (YES).. mediaserver rejects the request, bluetoothd then switches sendvolume to NO

**Comment by LNSSPsd** [comment]
No it's fine, the problem is on the `kBTAudioMsgPropertySupportRemoteVolumeChange=NO` property being sent right when the earbuds connect.

**Comment by rastafaa** [comment]
Yeah I see that, fyi the new latest edits don't seem to fix it in case you didn't already know. Possible to directly override mediaserver from ignoring the data? I guess you're not sure why it's being set to No value.

**Comment by LNSSPsd** [comment]
It's kind of an indirect way, and requires hooking on extra binaries.
Would try that if no other workable way found.

**Comment by rastafaa** [comment]
Yeah direct wasn't the right word I realize that's a bit of a hacky method I just meant it as a last resort I guess thanks for response.

**Comment by LNSSPsd** [comment]
I found the cause, probably:
I forgot to initialize the variable len!
```
char exec_path[512];
uint32_t len;
_NSGetExecutablePath(exec_path, &len);
```
Which end up with a zero-length and make the path comparison fails occasionally

**Comment by LNSSPsd** [comment]
Have a try on the latest one.

**Comment by rastafaa** [comment]
It works!! It only works while music/media is playing which I assume is normal? But this is awesome, thanks so much!

I'm not sure that optimized charging function is working as far as I can tell, but I'll have to use it more.

**Comment by Symplicityy** [comment]
> It works!! It only works while music/media is playing which I assume is normal? But this is awesome, thanks so much!
> 
> 
> 
> I'm not sure that optimized charging function is working as far as I can tell, but I'll have to use it more.

Volume works for me regardless of if any media is playing.

**Comment by rastafaa** [comment]
hm, yeah it doesn't work for me unless I have something playing.. that's why it didn't seem to be working at first. I'll restart phone though

**Comment by Symplicityy** [comment]
> hm, yeah it doesn't work for me unless I have something playing.. that's why it didn't seem to be working at first. I'll restart phone though

Well, that's better than it not working at all in calls like it does for me lol.

**Comment by rastafaa** [comment]
> Well, that's better than it not working at all in calls like it does for me lol.

Oh I thought you were LNSSPsd oops, but yeah at least it works with music. Does optimized charging work for you? I'm pretty sure mine isn't because it seems to always goto 100% charge which will degrade battery quicker so that sucks

**Comment by LNSSPsd** [comment]
> > Well, that's better than it not working at all in calls like it does for me lol.
> 
> Oh I thought you were LNSSPsd oops, but yeah at least it works with music. Does optimized charging work for you? I'm pretty sure mine isn't because it seems to always goto 100% charge which will degrade battery quicker so that sucks

I won't even care about mine's battery lol

**Comment by Symplicityy** [comment]
> > Well, that's better than it not working at all in calls like it does for me lol.
> 
> 
> 
> Oh I thought you were LNSSPsd oops, but yeah at least it works with music. Does optimized charging work for you? I'm pretty sure mine isn't because it seems to always goto 100% charge which will degrade battery quicker so that sucks

Haha all good. I can't tell if optimized charging works and I honestly don't even know what to look for.

**Comment by Symplicityy** [comment]
> > > Well, that's better than it not working at all in calls like it does for me lol.
> 
> > 
> 
> > Oh I thought you were LNSSPsd oops, but yeah at least it works with music. Does optimized charging work for you? I'm pretty sure mine isn't because it seems to always goto 100% charge which will degrade battery quicker so that sucks
> 
> 
> 
> I won't even care about mine's battery lol

AppleCare+ for AirPods is a super good deal so I got it for that exact reason. I'll just get a replacement in about a year if I'm having issues. I had my entire AirPods Pro 1st gen replaced right before the warranty was up. I was having an issue with the charging case not charging the AirPods and every time I went they kept telling me I had to replace the AirPods not the case so they replaced the buds about 3-5 times before they gave me a new case lol. So in the end I had brand new AirPods and a brand new case 2 years later.

**Comment by rastafaa** [comment]
> I can't tell if optimized charging works and I honestly don't even know what to look for.

It learns how you use the airpods and waits to charge fully to avoid battery wear. On my 1st gen pros it will typically goto 80% and the popup display will show that it's in optimized charging mode and presents a button to make it charge fully if you want. 

Usually don't need it fully charged it helps give it a longer lifespan. Airpod batteries aren't replaceable. I see the option in settings and have it enabled but don't think it's working on 2nd gen.

**Comment by Symplicityy** [comment]
> > I can't tell if optimized charging works and I honestly don't even know what to look for.
> 
> 
> 
> It learns how you use the airpods and waits to charge fully to avoid battery wear. On my 1st gen pros it will typically goto 80% and the popup display will show that it's in optimized charging mode and presents a button to make it charge fully if you want. 
> 
> 
> 
> Usually don't need it fully charged it helps give it a longer lifespan. Airpod batteries aren't replaceable. I see the option in settings and have it enabled but don't think it's working on 2nd gen.

Oh yea I'd want that disabled either way. My phone does that and it's always when I'm like 20% away from 100% and I'm trying to get it to 100 before I go to sleep and the disable button only works like 1/2 the time. But I'll let you know when I plug them in tonight if I get a pop up like that.

**Comment by rastafaa** [comment]
I restarted phone and still doesn't change volume unless media is playing 🤷‍♂️

**Comment by rastafaa** [comment]
I guess I mainly would use it to change volume while media is playing anyway so it's not a big deal, I'll see if it works during a call though
