### ISSUE TITLE
"Find My" Not Working

### ISSUE THREAD

**Issue by ChipSkylark37** [LNSSPsd/PodsGrant#56]
Hello,

I believe there may be an issue with using the "Find My" feature with AirPods Pro 2 with 15.0.1. 

I had once tried to use Find My by making the case beep, which didn't work, and now most times I open or close the case, it beeps as if it's locating it. The issue is it doesn't clear and I can't cancel the "locating"

Additionally, I will now get random alerts that "left" left behind and "right" left behind, even when the case and AirPods are in my pocket (in the case).this can happen anytime I'm traveling / driving / walking around with the case. It's like at some point when I put them back in the case, it detects that as the last location and then can't track them or the case anymore until I open it back up and it reconnects. 

Is there any way to support Find My? If not, I'm thinking the only way to stop it from trying to locate it constantly would be to unpair and repair the AirPods.

**Comment by DmitriiPl** [comment]
absolutely the same situation happened with me - this sounds are infuriating

**Comment by ChipSkylark37** [comment]
@LNSSPsd - Any ideas?

**Comment by bradleytechman** [comment]
I do not think it is possible to support find my.
