### ISSUE TITLE
求更新啊兄弟支持 c 口 pro

### ISSUE THREAD

**Issue by missyer** [LNSSPsd/PodsGrant#67]
求更新求更新求更新

**Comment by missyer** [comment]
求更新求更新

**Comment by missyer** [comment]
求更新求更新

**Comment by missyer** [comment]
给个指导手册 377413749@qq.com

**Comment by missyer** [comment]
更新一下吧，支持新款 airpods4 和新固件新功能吧！🙏🙏🙏
插件收费也可以的🙏🙏🙏🙏

**Comment by szxszxszx** [comment]
同求AirPods4

**Comment by missyer** [comment]
日常催更🌚

**Comment by missyer** [comment]
日常催更，收费都行

**Comment by missyer** [comment]
催更催更催更

**Comment by missyer** [comment]
催催催更😭

**Comment by missyer** [comment]
> > 催催催更😭
> 
> 
> 
> 你是真执着

那必须，既然你说了，我就再发一遍

**Comment by missyer** [comment]
日常催更更更更更更🙏🙏🙏🙏🙏

**Comment by Hmily001** [comment]
> > > 催催催更😭
> > 
> > 
> > 你是真执着
> 
> 那必须，既然你说了，我就再发一次

其实我在再等

**Comment by Hmily001** [comment]
> > > 催催催更😭
> > 
> > 
> > 你是真执着
> 
> 那必须，既然你说了，我就再发一遍

其实我也在等  但是中文你确定作者能看懂😭

**Comment by missyer** [comment]
日常催更，收费都可以🙏
