### ISSUE TITLE
[Request] Support for Air Pods Pro 2 (8228)

### ISSUE THREAD

**Issue by BB4LIFE** [LNSSPsd/PodsGrant#68]
Even with the custom product ID mapping, the tweak appears to not work. I mapped my AirPods Pro USB-C (8228) to AirPods Pro (8206), but my phone still seams to only support the limited features supported with the 2nd gen on iOS 15. I also tried mapping to other devices with the same result. For example, Spatial Audio does not support the head-tracking mode, and the adaptive transparency mode isn't an option to choose from. I understand that it is experimental. The main thing I would like, feature wise, is that feature though. However, I would also like it to where they seamlessly integrate with iOS 15. This would include the battery widgets properly showing the individual AirPod and case glyphs instead of them all looking like the generic headphones one. This would also allow them to appear in FindMy, so that I could control notifications for when they get left behind. Right now it just says something like "left" when they are away from me, and I can't choose to ignore notifications (it tries to open the Items tab for some reason). My current device is an iPhone 11 Pro on iOS 15.1 with Xina v2 jailbreak. This would be awesome to have, thanks.

Edit: Actually wrote a suggestion

**Comment by LNSSPsd** [comment]
I tried to implement USB-C version support on the latest pre-release, dk if it works
There was a bug on reading product ID mapping and that's why it wasn't working

**Comment by BB4LIFE** [comment]
@LNSSPsd Thank you so much for your work! I just tested the new version, and my phone definitely recognizes them as AirPods Pro 1st gen. It even enabled the Announce Notifications feature for me too. Adaptive Mode works but the toggle in settings doesn't. When I am in Noise Cancellation Mode, Adaptive Mode overrides it no matter the status of the toggle. If you could get it to work I would greatly appreciate it. Also I'm a little confused on what you meant by "Spatial Audio (Native)" because that has always seemed to work (unless your referring to it working on another model). The head-tracking function doesn't work, but I don't really care about that.
