### ISSUE TITLE
heard process repeatedly crashes

### ISSUE THREAD

**Issue by bradleytechman** [LNSSPsd/PodsGrant#71]
I have accumelated maybe **10,000** crash logs from the process `heard` I have been having this issue since version `0.3.0`, currently using `0.4.0~prerelease`. Cr4shed tells me the culprit is podsgrantadaptivetransparency.dylib, attached is a crashlog from KrashKop (as I accidentally cleared the log from cr4shed). I am using a iPhone 13 Pro Max on iOS 16.5 using Dopamine with AirPods Pro 2 USB-C.

[Crash Log](https://github.com/user-attachments/files/16809219/KrashKop.cr4shed.log.txt)

**Comment by LNSSPsd** [comment]
Fixed on 1aa534b012c03dc5c2e0ae873d7b29f1618a8e03.
