### ISSUE TITLE
airpods4

### ISSUE THREAD

**Issue by Kaws525** [LNSSPsd/PodsGrant#73]
Airpods 4 (active noise reduction version) cannot take effect on ios16.2. Please update it for him.

**Comment by AncientTree** [comment]
Is there anyone knows how to update for Airpod 4?

**Comment by LNSSPsd** [comment]
Anyone able to provide the product ID for AirPods 4?

**Comment by AncientTree** [comment]
> Anyone able to provide the product ID for AirPods 4?

Model Name: ACCESSORY_MODEL_NAME_27
Model Number: A3057

Is this help?

**Comment by Kaws525** [comment]
airpods4:A3057（8219）
This is the active noise reduction version, hope to help you

**Comment by Kaws525** [comment]
> 有人能提供AirPods 4的产品ID吗？

8219

**Comment by Hmily001** [comment]
waiting

**Comment by Kaws525** [comment]
Please update Airpods 4

**Comment by LNSSPsd** [comment]
Sorry guys been busy recently, commit 18ed868 probably solves this, closing this one for now

**Comment by AncientTree** [comment]
Thanks for your fruitful working, may I get a release *.deb file then? I don't know how to compile or update🥰

**Comment by LNSSPsd** [comment]
> Thanks for your fruitful working, may I get a release *.deb file then? I don't know how to compile or update🥰

Check `Releases` tab for 0.4 prerelease 2

**Comment by AncientTree** [comment]
Got it!

**Comment by TwilightMercy** [comment]
Hi, does it work for Airpods 4 ANC + iOS 16.4?
