### ISSUE TITLE
AirPods Pro 2 - USB C on 16.4.1

### ISSUE THREAD

**Issue by deep0d0** [LNSSPsd/PodsGrant#75]
Hi there!

I tested using PreRelease 0.4.0 ~ 1 and it causes crash of Bluetooth when using anything other than AirPods, such as cad stereo etc.

so I’ve had to remove for now. But it’s a bad experience without PodsGrant because no battery info, Siri announcements etc.

please help! I can provide assistance in debug or whatever is needed

**Comment by deep0d0** [comment]
Attaching my Bluetoothd file here 
[bluetoothd.zip](https://github.com/user-attachments/files/17346376/bluetoothd.zip)

**Comment by LNSSPsd** [comment]
Could you provide any logs related to the crashes? You might be able to get them by searching `bluetoothd` or `sharingd` at `Settings > Privacy > Analytics & Improvements > Analytics Data`.

**Comment by fyrehero** [comment]
[bluetoothd-2024-12-18-230002.txt](https://github.com/user-attachments/files/18192192/bluetoothd-2024-12-18-230002.txt)


Same issue with bluetoothd crashing, also using AirPods Pro 2 USB-C on 16.4.1, attached my log.

**Comment by LNSSPsd** [comment]
Seems iOS 16.4.1 has a different bluetoothd binary than iOS 16.4, please check [prerelase 3](https://github.com/LNSSPsd/PodsGrant/releases/tag/0.4.0-prerelease-3).

**Comment by deep0d0** [comment]
Tried the new pre-release, working very well so far. Annouce Notifications and other stuff is now working. Best!
