### ISSUE TITLE
[BUG] After I install PodsGrant, some of others known bluetooth devices can't pair. Only uninstalling PodsGrant resolve.

### ISSUE THREAD

**Issue by AncientTree** [LNSSPsd/PodsGrant#76]
Is there any Idea? If log is available, please let me know how to catch it 😁

**Comment by LNSSPsd** [comment]
Hi, do you mind sharing your iOS version?

**Comment by AncientTree** [comment]
iOS 16.4.1 here.

there is a bug: my car Bluetooth  loudspeaker can't pairs to iPhone if I have installed this plugin. Specifically, when I wanted to pair other Bluetooth speakers, the iPhone's Bluetooth automatically restarted. The problem disappeared after I uninstalled the plugin.

Since you know how plugins work, perhaps you can easily guess which parts of the code are causing this bug.

I'm not sure this bug will be replicated in other iOS versions.

Anyway, thanks for your work.

**Comment by AncientTree** [comment]
Okay, I will try this tomorrow.

**Comment by AncientTree** [comment]
solved😁
