### ISSUE TITLE
AirPods Pro 2nd Gen USB C are appearing as 1st Gen

### ISSUE THREAD

**Issue by AbsR99** [LNSSPsd/PodsGrant#77]
On the pre-release 0.4.0 the USB C Pros are appearing as first gen pros. I can’t get them to work as Pro 2nd gen, so no find my I guess.

To fix it, I’ve tried removing the presets I don’t need and build the tweak using my Mac but I keep getting error code 2 along with a bunch of errors I barely understand. Something to do what adaptive transparency…

**Comment by LNSSPsd** [comment]
This tweak doesn't do anything on FindMy so far so that's kind of expected ig..

Second generation earbuds will appear as first gen for iOS versions below 16 bc they don't natively support second gen (or does iOS 15? I don't quite remember correct me if so)

**Comment by AbsR99** [comment]
I’m on ios 16, so they should work for me, but for some reason I’ve had so many issues with jb tweaks on 16.0.2 it’s probably a fault with my device and not your tweak, so imma close this. Thanks so much for your help.
