### ISSUE TITLE
Where should I go to download the latest deb file, bigboss only has version 0.1.0

### ISSUE THREAD

**Issue by babyf2sh** [LNSSPsd/PodsGrant#8]
Where should I go to download the latest deb file, bigboss only has version 0.1.0

**Comment by LNSSPsd** [comment]
Don't worry, it would be there soon.
And for iOS 15.* (rootless), releases would only be available in github releases as bigboss does not support rootless.

**Comment by babyf2sh** [comment]
> Don't worry, it would be there soon.
> And for iOS 15.* (rootless), releases would only be available in github releases as bigboss does not support rootless.

I have system 14.1, I need the latest DEB file to install.

**Comment by rastafaa** [comment]
> > Don't worry, it would be there soon.
> > And for iOS 15.* (rootless), releases would only be available in github releases as bigboss does not support rootless.
> 
> I have system 14.1, I need the latest DEB file to install.

he just said it'll release soon

**Comment by LNSSPsd** [comment]
[Releases](https://github.com/LNSSPsd/PodsGrant/releases/tag/0.2.0) or bigboss in a few days
